package net.minecraft.item;

public final class ModernItemCatalog {
    public static final String[][] ITEMS = {
        {"acacia_chest_boat", "Acacia Boat with Chest"},
        {"allay_spawn_egg", "Allay Spawn Egg"},
        {"amethyst_shard", "Amethyst Shard"},
        {"angler_pottery_sherd", "Angler Pottery Sherd"},
        {"archer_pottery_sherd", "Archer Pottery Sherd"},
        {"armadillo_scute", "Armadillo Scute"},
        {"armadillo_spawn_egg", "Armadillo Spawn Egg"},
        {"arms_up_pottery_sherd", "Arms Up Pottery Sherd"},
        {"axolotl_bucket", "Bucket of Axolotl"},
        {"axolotl_spawn_egg", "Axolotl Spawn Egg"},
        {"bamboo_chest_raft", "Bamboo Raft with Chest"},
        {"bamboo_raft", "Bamboo Raft"},
        {"bee_spawn_egg", "Bee Spawn Egg"},
        {"birch_chest_boat", "Birch Boat with Chest"},
        {"black_bundle", "Black Bundle"},
        {"black_harness", "Black Harness"},
        {"blade_pottery_sherd", "Blade Pottery Sherd"},
        {"blue_bundle", "Blue Bundle"},
        {"blue_egg", "Blue Egg"},
        {"blue_harness", "Blue Harness"},
        {"bogged_spawn_egg", "Bogged Spawn Egg"},
        {"bolt_armor_trim_smithing_template", "Bolt Armor Trim Smithing Template"},
        {"bordure_indented_banner_pattern", "Bordure Indented Banner Pattern"},
        {"breeze_rod", "Breeze Rod"},
        {"breeze_spawn_egg", "Breeze Spawn Egg"},
        {"brewer_pottery_sherd", "Brewer Pottery Sherd"},
        {"brown_bundle", "Brown Bundle"},
        {"brown_egg", "Brown Egg"},
        {"brown_harness", "Brown Harness"},
        {"brush", "Brush"},
        {"bundle", "Bundle"},
        {"burn_pottery_sherd", "Burn Pottery Sherd"},
        {"camel_husk_spawn_egg", "Camel Husk Spawn Egg"},
        {"camel_spawn_egg", "Camel Spawn Egg"},
        {"cherry_boat", "Cherry Boat"},
        {"cherry_chest_boat", "Cherry Boat with Chest"},
        {"coast_armor_trim_smithing_template", "Coast Armor Trim Smithing Template"},
        {"cod_bucket", "Bucket of Cod"},
        {"cod_spawn_egg", "Cod Spawn Egg"},
        {"copper_axe", "Copper Axe"},
        {"copper_boots", "Copper Boots"},
        {"copper_chestplate", "Copper Chestplate"},
        {"copper_golem_spawn_egg", "Copper Golem Spawn Egg"},
        {"copper_helmet", "Copper Helmet"},
        {"copper_hoe", "Copper Hoe"},
        {"copper_horse_armor", "Copper Horse Armor"},
        {"copper_ingot", "Copper Ingot"},
        {"copper_leggings", "Copper Leggings"},
        {"copper_nautilus_armor", "Copper Nautilus Armor"},
        {"copper_nugget", "Copper Nugget"},
        {"copper_pickaxe", "Copper Pickaxe"},
        {"copper_shovel", "Copper Shovel"},
        {"copper_spear", "Copper Spear"},
        {"copper_sword", "Copper Sword"},
        {"creaking_spawn_egg", "Creaking Spawn Egg"},
        {"creeper_banner_pattern", "Creeper Banner Pattern"},
        {"crossbow", "Crossbow"},
        {"cyan_bundle", "Cyan Bundle"},
        {"cyan_harness", "Cyan Harness"},
        {"danger_pottery_sherd", "Danger Pottery Sherd"},
        {"dark_oak_chest_boat", "Dark Oak Boat with Chest"},
        {"debug_stick", "Debug Stick"},
        {"diamond_nautilus_armor", "Diamond Nautilus Armor"},
        {"diamond_spear", "Diamond Spear"},
        {"disc_fragment_5", "Disc Fragment"},
        {"dolphin_spawn_egg", "Dolphin Spawn Egg"},
        {"dried_kelp", "Dried Kelp"},
        {"drowned_spawn_egg", "Drowned Spawn Egg"},
        {"dune_armor_trim_smithing_template", "Dune Armor Trim Smithing Template"},
        {"echo_shard", "Echo Shard"},
        {"ender_dragon_spawn_egg", "Ender Dragon Spawn Egg"},
        {"explorer_pottery_sherd", "Explorer Pottery Sherd"},
        {"eye_armor_trim_smithing_template", "Eye Armor Trim Smithing Template"},
        {"field_masoned_banner_pattern", "Field Masoned Banner Pattern"},
        {"flow_armor_trim_smithing_template", "Flow Armor Trim Smithing Template"},
        {"flow_banner_pattern", "Flow Banner Pattern"},
        {"flow_pottery_sherd", "Flow Pottery Sherd"},
        {"flower_banner_pattern", "Flower Banner Pattern"},
        {"fox_spawn_egg", "Fox Spawn Egg"},
        {"friend_pottery_sherd", "Friend Pottery Sherd"},
        {"frog_spawn_egg", "Frog Spawn Egg"},
        {"globe_banner_pattern", "Globe Banner Pattern"},
        {"glow_berries", "Glow Berries"},
        {"glow_ink_sac", "Glow Ink Sac"},
        {"glow_item_frame", "Glow Item Frame"},
        {"glow_squid_spawn_egg", "Glow Squid Spawn Egg"},
        {"goat_horn", "Goat Horn"},
        {"goat_spawn_egg", "Goat Spawn Egg"},
        {"golden_nautilus_armor", "Golden Nautilus Armor"},
        {"golden_spear", "Golden Spear"},
        {"gray_bundle", "Gray Bundle"},
        {"gray_harness", "Gray Harness"},
        {"green_bundle", "Green Bundle"},
        {"green_harness", "Green Harness"},
        {"guster_banner_pattern", "Guster Banner Pattern"},
        {"guster_pottery_sherd", "Guster Pottery Sherd"},
        {"happy_ghast_spawn_egg", "Happy Ghast Spawn Egg"},
        {"harness", "Harness"},
        {"heart_of_the_sea", "Heart of the Sea"},
        {"heart_pottery_sherd", "Heart Pottery Sherd"},
        {"heartbreak_pottery_sherd", "Heartbreak Pottery Sherd"},
        {"hoglin_spawn_egg", "Hoglin Spawn Egg"},
        {"honey_bottle", "Honey Bottle"},
        {"honeycomb", "Honeycomb"},
        {"host_armor_trim_smithing_template", "Host Armor Trim Smithing Template"},
        {"howl_pottery_sherd", "Howl Pottery Sherd"},
        {"iron_nautilus_armor", "Iron Nautilus Armor"},
        {"iron_spear", "Iron Spear"},
        {"jungle_chest_boat", "Jungle Boat with Chest"},
        {"leather_horse_armor", "Leather Horse Armor"},
        {"light_blue_bundle", "Light Blue Bundle"},
        {"light_blue_harness", "Light Blue Harness"},
        {"light_gray_bundle", "Light Gray Bundle"},
        {"light_gray_harness", "Light Gray Harness"},
        {"lime_bundle", "Lime Bundle"},
        {"lime_harness", "Lime Harness"},
        {"lodestone_compass", "Lodestone Compass"},
        {"mace", "Mace"},
        {"magenta_bundle", "Magenta Bundle"},
        {"magenta_harness", "Magenta Harness"},
        {"mangrove_boat", "Mangrove Boat"},
        {"mangrove_chest_boat", "Mangrove Boat with Chest"},
        {"miner_pottery_sherd", "Miner Pottery Sherd"},
        {"mojang_banner_pattern", "Mojang Banner Pattern"},
        {"mourner_pottery_sherd", "Mourner Pottery Sherd"},
        {"music_disc_5", "Music Disc 5"},
        {"music_disc_bounce", "Music Disc Bounce"},
        {"music_disc_creator", "Music Disc Creator"},
        {"music_disc_creator_music_box", "Music Disc Creator Music Box"},
        {"music_disc_lava_chicken", "Music Disc Lava Chicken"},
        {"music_disc_otherside", "Music Disc Otherside"},
        {"music_disc_pigstep", "Music Disc Pigstep"},
        {"music_disc_precipice", "Music Disc Precipice"},
        {"music_disc_relic", "Music Disc Relic"},
        {"music_disc_tears", "Music Disc Tears"},
        {"nautilus_shell", "Nautilus Shell"},
        {"nautilus_spawn_egg", "Nautilus Spawn Egg"},
        {"netherite_axe", "Netherite Axe"},
        {"netherite_boots", "Netherite Boots"},
        {"netherite_chestplate", "Netherite Chestplate"},
        {"netherite_helmet", "Netherite Helmet"},
        {"netherite_hoe", "Netherite Hoe"},
        {"netherite_horse_armor", "Netherite Horse Armor"},
        {"netherite_ingot", "Netherite Ingot"},
        {"netherite_leggings", "Netherite Leggings"},
        {"netherite_nautilus_armor", "Netherite Nautilus Armor"},
        {"netherite_pickaxe", "Netherite Pickaxe"},
        {"netherite_scrap", "Netherite Scrap"},
        {"netherite_shovel", "Netherite Shovel"},
        {"netherite_spear", "Netherite Spear"},
        {"netherite_sword", "Netherite Sword"},
        {"netherite_upgrade_smithing_template", "Netherite Upgrade Smithing Template"},
        {"oak_chest_boat", "Oak Boat with Chest"},
        {"ominous_bottle", "Ominous Bottle"},
        {"ominous_trial_key", "Ominous Trial Key"},
        {"orange_bundle", "Orange Bundle"},
        {"orange_harness", "Orange Harness"},
        {"pale_oak_boat", "Pale Oak Boat"},
        {"pale_oak_chest_boat", "Pale Oak Boat with Chest"},
        {"panda_spawn_egg", "Panda Spawn Egg"},
        {"parched_spawn_egg", "Parched Spawn Egg"},
        {"phantom_membrane", "Phantom Membrane"},
        {"phantom_spawn_egg", "Phantom Spawn Egg"},
        {"piglin_banner_pattern", "Piglin Banner Pattern"},
        {"piglin_brute_spawn_egg", "Piglin Brute Spawn Egg"},
        {"piglin_spawn_egg", "Piglin Spawn Egg"},
        {"pillager_spawn_egg", "Pillager Spawn Egg"},
        {"pink_bundle", "Pink Bundle"},
        {"pink_harness", "Pink Harness"},
        {"pitcher_plant", "Pitcher Plant"},
        {"pitcher_pod", "Pitcher Pod"},
        {"plenty_pottery_sherd", "Plenty Pottery Sherd"},
        {"powder_snow_bucket", "Powder Snow Bucket"},
        {"prize_pottery_sherd", "Prize Pottery Sherd"},
        {"pufferfish_bucket", "Bucket of Pufferfish"},
        {"pufferfish_spawn_egg", "Pufferfish Spawn Egg"},
        {"purple_bundle", "Purple Bundle"},
        {"purple_harness", "Purple Harness"},
        {"raiser_armor_trim_smithing_template", "Raiser Armor Trim Smithing Template"},
        {"ravager_spawn_egg", "Ravager Spawn Egg"},
        {"raw_copper", "Raw Copper"},
        {"raw_gold", "Raw Gold"},
        {"raw_iron", "Raw Iron"},
        {"recovery_compass", "Recovery Compass"},
        {"red_bundle", "Red Bundle"},
        {"red_harness", "Red Harness"},
        {"resin_brick", "Resin Brick"},
        {"resin_clump", "Resin Clump"},
        {"rib_armor_trim_smithing_template", "Rib Armor Trim Smithing Template"},
        {"salmon_bucket", "Bucket of Salmon"},
        {"salmon_spawn_egg", "Salmon Spawn Egg"},
        {"scrape_pottery_sherd", "Scrape Pottery Sherd"},
        {"sentry_armor_trim_smithing_template", "Sentry Armor Trim Smithing Template"},
        {"shaper_armor_trim_smithing_template", "Shaper Armor Trim Smithing Template"},
        {"sheaf_pottery_sherd", "Sheaf Pottery Sherd"},
        {"shelter_pottery_sherd", "Shelter Pottery Sherd"},
        {"silence_armor_trim_smithing_template", "Silence Armor Trim Smithing Template"},
        {"skull_banner_pattern", "Skull Banner Pattern"},
        {"skull_pottery_sherd", "Skull Pottery Sherd"},
        {"smithing_template", "Smithing Template"},
        {"sniffer_spawn_egg", "Sniffer Spawn Egg"},
        {"snort_pottery_sherd", "Snort Pottery Sherd"},
        {"snout_armor_trim_smithing_template", "Snout Armor Trim Smithing Template"},
        {"spire_armor_trim_smithing_template", "Spire Armor Trim Smithing Template"},
        {"spruce_chest_boat", "Spruce Boat with Chest"},
        {"spyglass", "Spyglass"},
        {"stone_spear", "Stone Spear"},
        {"strider_spawn_egg", "Strider Spawn Egg"},
        {"sulfur_cube_bucket", "Bucket of Sulfur Cube"},
        {"sulfur_cube_spawn_egg", "Sulfur Cube Spawn Egg"},
        {"suspicious_stew", "Suspicious Stew"},
        {"sweet_berries", "Sweet Berries"},
        {"tadpole_bucket", "Bucket of Tadpole"},
        {"tadpole_spawn_egg", "Tadpole Spawn Egg"},
        {"tide_armor_trim_smithing_template", "Tide Armor Trim Smithing Template"},
        {"torchflower_seeds", "Torchflower Seeds"},
        {"trader_llama_spawn_egg", "Trader Llama Spawn Egg"},
        {"trial_key", "Trial Key"},
        {"trident", "Trident"},
        {"tropical_fish_bucket", "Bucket of Tropical Fish"},
        {"tropical_fish_spawn_egg", "Tropical Fish Spawn Egg"},
        {"turtle_spawn_egg", "Turtle Spawn Egg"},
        {"vex_armor_trim_smithing_template", "Vex Armor Trim Smithing Template"},
        {"wandering_trader_spawn_egg", "Wandering Trader Spawn Egg"},
        {"ward_armor_trim_smithing_template", "Ward Armor Trim Smithing Template"},
        {"warden_spawn_egg", "Warden Spawn Egg"},
        {"warped_fungus_on_a_stick", "Warped Fungus on a Stick"},
        {"wayfinder_armor_trim_smithing_template", "Wayfinder Armor Trim Smithing Template"},
        {"white_bundle", "White Bundle"},
        {"white_harness", "White Harness"},
        {"wild_armor_trim_smithing_template", "Wild Armor Trim Smithing Template"},
        {"wind_charge", "Wind Charge"},
        {"wolf_armor", "Wolf Armor"},
        {"wooden_spear", "Wooden Spear"},
        {"yellow_bundle", "Yellow Bundle"},
        {"yellow_harness", "Yellow Harness"},
        {"zoglin_spawn_egg", "Zoglin Spawn Egg"},
        {"zombie_nautilus_spawn_egg", "Zombie Nautilus Spawn Egg"}
    };

    private ModernItemCatalog() {
    }
}
